### ISSUE TITLE
Feature: Prefix option for calculated image reference

### ISSUE THREAD

**Issue by georgegillams** [lucsorel/markdown-image-loader#2]
Hey 👋 

We're facing a small issue with this loader. It's converting the image src correctly but without a `/` at the start of the path. That means when we render the markdown, browsers try to load from the current URL instead of the root URL.

`![test image](/my-image.png)` => `![test image](my-image_ec3fbba949c04f7cf52dd40e8b68d41e.png)`

Maybe we're doing something wrong, in which case you may have a fix in mind already? If not, I would be happy to contribute something to fix this.

In terms of contribution, I'm thinking maybe an option called `pathPrefix` for the loader that would be inserted at the start of the image src?

`![test image](/my-image.png)` => `![test image](<OPTIONAL_PATH_PREFIX>my-image_ec3fbba949c04f7cf52dd40e8b68d41e.png)`

**Comment by lucsorel** [comment]
Hi @georgegillams.

Thank you for reporting your problem. I will have a look at it tomorrow. Stay tuned :)

**Comment by lucsorel** [comment]
Hi @georgegillams,

Your needs regarding the naming of the files or their URL prefix and so on can be met by setting the appropriate [file-loader options](https://webpack.js.org/loaders/file-loader/#options). In your case, I think you should set `publicPath` to `'/'`. Let me know if it solved your case.

I documented more explicitly this point in the README.file of #3.

**Comment by georgegillams** [comment]
Thank you so much @lucsorel. We'll give that a try 👍
