### ISSUE TITLE
Webpack 5

### ISSUE THREAD

**Issue by clauderobi** [lucsorel/markdown-image-loader#7]
Is it working under Webpack 5? If so it is possible to update the dependency?

**Comment by lucsorel** [comment]
hi @clauderobi 
I have no idea whether it work with webpack 5 or not. I have not checked what are the breaking changes between wp 4 and 5; could you provide a document which would help me answer your question.

Can you give it a try and let me know, please?

**Comment by clauderobi** [comment]
It probably works. Actually, what I saw was that the **webpack_require** stuff is present in the bundle.js file and appears to be Ok. I also see that the build directory includes the referenced image file. However, the imported markdown text has this: ![test2]([object Module]), which does not look Ok to me. How could the renderer find the correct image file content with just "object Module"?

Can I make a documentation suggestion? I came here from markdown-loader, with which I am not able to get the image file link properly processed. markdown-loader not only loads the markdown text but renders it under the hood my calling marked automatically. I was under the impression that mardown-image-loader would do the same since I did not understood that Reveal and remark are renderers that you call manually (sort of); I did not know them at the time I first read your README.md so I skipped that part. May be making more clear that rendering is something that needs to be handled outside markdown-image-loader would help.

**Comment by lucsorel** [comment]
`![test2]([object Module])` is definitely due to a breaking change. I will take a look when I can but it won't be very soon. I've kind of moved on to python libraries for the moment :cry:

**Comment by hardiksukhadiya** [comment]
Hi @lucsorel for me it is working fine in webpack 5 and I did the required changes in peerDependencies and also run all the test cases and all are working fine. So can you please check this [PR](https://github.com/lucsorel/markdown-image-loader/pull/9)  and merge it if that is fine for you? or please add the required comments for the same if there is any observation.

**Comment by hardiksukhadiya** [comment]
> 

@clauderobi ![test2]([object Module]) this could be handled outside markdown-image-loader in webpack config file. 
You can enable file-loader's CommonJS module syntax, which webpack will resolve directly to the module itself. Set esModule:false in your webpack config.

webpack.config.js:

 ```
{
        test: /\.(png|svg|jpg|jpeg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              outputPath: "assets",
              name: "[path][name].[contenthash].[ext]",
              esModule: false,
            },
          },
        ],
}
```

If you want to know about in details for this  [object Module] which file loader generates by-default then please read below document where a developer explained this thing in details.
https://stackoverflow.com/questions/59070216/webpack-file-loader-outputs-object-module

**Comment by lucsorel** [comment]
closed by https://github.com/lucsorel/markdown-image-loader/pull/9
